name: Deploy Front Stage

on:
  push:
    branches: [stage]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check index.html
        run: test -f index.html

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to stage server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: 95.38.191.201
          username: deept
          key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHfFBwF9cTDUg0oMWQ9KoXfGfB8iywrwvIA6qj1iLf0c github-actions-stage
          script: |
            /var/www/deept/deploy-front-stage.sh