name: Deploy Front Main

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check index.html
        run: test -f index.html

  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to main server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host:  ${{ secrets.MAIN_SERVER_HOST }}
          username: ${{ secrets.MAIN_SERVER_USER }}
          key: ${{ secrets.MAIN_SERVER_SSH_KEY }}

          debug: true
          script: |
            /var/www/deept/deploy-front-main.sh